# Generated by Django 2.2.12 on 2020-12-28 07:16

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
                ('is_Delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_img', models.ImageField(upload_to='product_img')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_Delete', models.BooleanField(default=False)),
                ('product_click', models.IntegerField(default=0)),
                ('product_unit', models.CharField(max_length=20)),
                ('product_abstract', models.CharField(max_length=120)),
                ('product_stock', models.IntegerField()),
                ('product_content', tinymce.models.HTMLField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductType')),
            ],
        ),
    ]
